//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HermesCsharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cliente()
        {
            this.reserva = new HashSet<reserva>();
            this.detalleReservaViajero = new HashSet<detalleReservaViajero>();
        }
    
        public int idCliente { get; set; }
        public int idUsuario { get; set; }
        public string numeroContacto { get; set; }
        public string direccion { get; set; }
        public int idMunicipio { get; set; }
        public string sexo { get; set; }
        public string tipoDeSangre { get; set; }
        public string eps { get; set; }
        public bool estadoCliente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reserva> reserva { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalleReservaViajero> detalleReservaViajero { get; set; }
        public virtual municipio municipio { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
