//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HermesCsharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detallePaqueteServicio
    {
        public int idDetallePaqueteServicio { get; set; }
        public int idPaquete { get; set; }
        public int idServicio { get; set; }
        public int cantidadServicioPaquete { get; set; }
        public Nullable<decimal> valorServicioPaquete { get; set; }
    
        public virtual paquete paquete { get; set; }
        public virtual servicio servicio { get; set; }
    }
}
