//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HermesCsharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalleReservaViajero
    {
        public int idDetalleReservaViajero { get; set; }
        public int idReserva { get; set; }
        public int idCliente { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual reserva reserva { get; set; }
    }
}
