//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HermesCsharp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RelationContext : DbContext
    {
        public RelationContext()
            : base("name=RelationContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<actividad> actividad { get; set; }
        public virtual DbSet<categoriaServicio> categoriaServicio { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<departamento> departamento { get; set; }
        public virtual DbSet<detallePaqueteServicio> detallePaqueteServicio { get; set; }
        public virtual DbSet<detalleReservaViajero> detalleReservaViajero { get; set; }
        public virtual DbSet<municipio> municipio { get; set; }
        public virtual DbSet<pago> pago { get; set; }
        public virtual DbSet<pais> pais { get; set; }
        public virtual DbSet<paquete> paquete { get; set; }
        public virtual DbSet<permiso> permiso { get; set; }
        public virtual DbSet<privilegio> privilegio { get; set; }
        public virtual DbSet<programacion> programacion { get; set; }
        public virtual DbSet<reserva> reserva { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<rolPrivilegio> rolPrivilegio { get; set; }
        public virtual DbSet<servicio> servicio { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
