//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HermesCsharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class servicio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public servicio()
        {
            this.detallePaqueteServicio = new HashSet<detallePaqueteServicio>();
        }
    
        public int idServicio { get; set; }
        public int idCategoriaServicio { get; set; }
        public string nombreServicio { get; set; }
        public decimal valorServicio { get; set; }
        public bool estadoServicio { get; set; }
    
        public virtual categoriaServicio categoriaServicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detallePaqueteServicio> detallePaqueteServicio { get; set; }
    }
}
